apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movie-finder
  name: movie-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-finder
  strategy: {}
  template:
    metadata:
      labels:
        app: movie-finder
    spec:
      containers:
      - image: 192.168.1.8:5000/dealscandy/movie-finder:latest
        imagePullPolicy: Always
        name: movie-finder        
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: movie-finder
    name: movie-finder
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: movie-finder
    type: NodePort  
