apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: movie-finder
  name: movie-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-finder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: movie-finder
    spec:
      containers:
      - image: 192.168.1.8/movie-finder:1
        name: movie-finder
        resources: {}
status: {}
