apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: movie-finder
  name: movie-finder
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: movie-finder
  type: NodePort
status:
  loadBalancer: {}
